apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-generator
  labels:
    app: pdf-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-generator
  template:
    metadata:
      labels:
        app: pdf-generator
    spec:
      containers:
      - name: pdf-generator
        image: 172.22.121.50/personnel-matching/zwx/pdf-generator:$CI_PIPELINE_IID
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: pdf-generator
spec:
  type: NodePort
  selector:
    app: pdf-generator
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
